version: '3'
services:
  web:
    image: fpfis/php71-dev
    environment:
      - DOCUMENT_ROOT=${PWD}/web
    ports:
      - 80:8080
      - 443:8080
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
  mysql:
    image: percona/percona-server:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=drupal
  selenium:
    image: selenium/standalone-chrome
  # solr:
  #   image: fpfis/solr5